name = "PeriodicOrbits"
uuid = "41be5fce-5647-450b-ae37-a6739b881a1c"
repo = "https://github.com/JuliaDynamics/PeriodicOrbits.jl.git"
version = "0.1.0"

[deps]
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DynamicalSystemsBase = "3.8"
Reexport = "1"
julia = "1.9"
